name: Fly
description: Pd with Fly demonstration

app:
  startCommand:
    - C:\MRLab\Audio-Apps\Demo-Fly\_OPEN DEMO.bat

  stopCommand:
    - C:\Windows\System32\taskkill
    - /IM
    - pd.com
    - /T
    - /F

  workingDir: C:\MRLab\Audio-Apps\Demo-Fly

  oscClients:
    - id: yami
      subPath: osc
      listenPort: 9336
      destination: [ localhost, 10003 ]
