name: Jungle
description: Pd with Jungle demonstration

app:
  startCommand:
    - C:\MRLab\Audio-Apps\Demo-Jungle\_OPEN DEMO.bat

  stopCommand:
    - C:\Windows\System32\taskkill
    - /IM
    - pd.com
    - /T
    - /F

  workingDir: C:\MRLab\Audio-Apps\Demo-Jungle

  oscClients:
    - id: pd_jungle
      subPath: osc
      listenPort: 9336
      destination: [ localhost, 10003 ]
