name: Reaper Music
description: Reaper DAW with music example

app:
  startCommand:
    - C:\Program Files\REAPER (x64)\reaper
    - C:\MRLab\Audio-Apps\Demo-Music\music.rpp

  stopCommand: []

  workingDir: ""

  oscClients:
    - id: reaper
      subPath: osc
      listenPort: 9342
      destination: [ localhost, 10009 ]
