name: Reaper Reverb
description: Reaper DAW with artificial reverb

app:
  startCommand:
    - C:\Program Files\REAPER (x64)\reaper
    - C:\MRLab\Audio-Apps\Demo-Realtime Reverb\realtime reverb.rpp

  stopCommand: []

  workingDir: ""

  oscClients:
    - id: reaper
      subPath: osc
      listenPort: 9338
      destination: [ localhost, 10005 ]
