name: Stereo Walls
description: Pd with Walls playing a stereo signal

app:
  startCommand:
    - C:\MRLab\Audio-Apps\SA-VBAP\_LAUNCH SCENE.bat

  stopCommand:
    - C:\Windows\System32\taskkill
    - /IM
    - pd.com
    - /T
    - /F

  workingDir: C:\MRLab\Audio-Apps\SA-VBAP

  oscClients:
    - id: sa_vbap
      subPath: osc
      listenPort: 9336
      destination: [ localhost, 10003 ]
